### PR TITLE
Adds an explanation to the quit page

### PR DESCRIPTION
**Pull request by laurensmartina**
At the quit page, it was unclear what the user could expect.
This fixes that problem.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
The commit also changes the button text, @laurensmartina, perhaps you could add that in the commit message?

@all, what do you think of this change/wording? Here's how it looks with this PR:

image
image
image
image


Personally, I wouldn't mind removing the "Screw you guys..." text, just leave the textbox empty by default?

**Comment by laurensmartina** [comment]
I think it's fine for now.. It can be further improved if needed.

**Comment by dianawi** [comment]
I think it is good, and yes, let's take out the screw you guys text.

**Comment by matthijskooijman** [comment]
I've removed the "Screw you..." wording, and rebased. Ready to merge now.

**Pull request merged**
