### PR TITLE
Added logo so no need for external call

### PR DESCRIPTION
**Pull request by tammoterhark**
Addressing: https://github.com/PlanBCode/hypha/issues/19

### CODE REVIEW

**Comment by matthijskooijman** [comment]
I do not really like adding (extra) separate files to the root, but I'm not sure if we currently have a better place for this. Perhaps a new directory can be created, to also hold the base CSS when #18 is implemented?

**Comment by giplt** [comment]
How about placing it in /data/images?

**Comment by tammoterhark** [comment]
As it is now, the image is referred to from hypha.xml, which lives in /data, so yes, the image should go in /data/images. That is where I placed it.

**Comment by tammoterhark** [comment]
Te vroeg, wil nog even verder spelen.

**Pull request closed without merging**
