### PR TITLE
Adds CSS class to index item indicating public or private state

### PR DESCRIPTION
**Pull request by laurensmartina**
In order to be more flexible in the way the index items can be styled a
CSS class, indicating the public of private state, is added.

### CODE REVIEW

**Comment by tammoterhark** [comment]
I very much like this, but it is not a way for getting rid of the asterisk, which was ment to indicate that a page was not published yet. So I would also like a class indicating the status of the content type. This could be a class that is shown only when the page is not published yet, like .is_not_published

**Comment by laurensmartina** [comment]
> I very much like this, but it is not a way for getting rid of the asterisk, which was ment to indicate that a page was not published yet.

Unfortunately I don't understand what you mean. Do you want to keep the asterisk?

> So I would also like a class indicating the status of the content type. This could be a class that is shown only when the page is not published yet, like .is_not_published

You can accomplish the same with 'is-public' and 'is-private' as you could with 'is_not_published'. Furthermore more consistent to indicate what something is in stead of indication what something is not.

**Comment by giplt** [comment]
Just to be clear, an asterisk doesn't indicate 'not yet published page' but 'private page' as opposed to 'public page'. Recent focus on peer reviewed article content (De Stadsbron) may suggest that the end state of each and any page should be public. However, hypha should facilitate sharing of information within a project group just as well as updating the rest of the world about it. So maybe the difference between the state of a page (private/public) and the state of an article (draft/review/approved/published) is a little confusing here?

**Comment by tammoterhark** [comment]
I guess so.

If what Harmen wrote is true, he mostly is, than I withdraw my comment and
I approve of this PR.

**Comment by tammoterhark** [comment]
yes, but: so what?

An asterisk is a solution, could also be another color of the text, another
font(-weight/-size) etc. These decisions are up to the designer.

Op za 4 jan. 2020 om 19:19 schreef Matthijs Kooijman <
notifications@github.com>:

**Comment by matthijskooijman** [comment]
> An asterisk is a solution, could also be another color of the text, another
font(-weight/-size) etc. These decisions are up to the designer.

Yes, but the default theme should also be usable, so that should somehow indicate private pages as before. Lacking an incentive to change things, I would suggest preserving the asterisk (but through CSS so it can be customized). If we *also* want to change the default design, that's also fine by me, but then we should pick something else. If we want to change the default design to *not* show private pages anymore, then that's also fine, as long as it is an explicit choice (which should then be documented in the commit message at least). I have no real preference here.

**Comment by laurensmartina** [comment]
> > An asterisk is a solution, could also be another color of the text, another
> > font(-weight/-size) etc. These decisions are up to the designer.
> 
> Yes, but the default theme should also be usable, so that should somehow indicate private pages as before. Lacking an incentive to change things, I would suggest preserving the asterisk (but through CSS so it can be customized). If we _also_ want to change the default design, that's also fine by me, but then we should pick something else. If we want to change the default design to _not_ show private pages anymore, then that's also fine, as long as it is an explicit choice (which should then be documented in the commit message at least). I have no real preference here.

Fixed!

**Pull request merged**
