### PR TITLE
Article buttons at end

### PR DESCRIPTION
**Pull request by matthijskooijman**
This adds some buttons at the end of the article view and edit pages. It also refactors some code.

These commits are copied from #149 with some minor improvements and a rebase. Not all commits are included, some will be used later for #199 instead.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
In particular, this adds an "approve link" at the bottom of an article view page:

image

And it adds ok/cancel buttons to the end of the article edit interface:

image


@all, how does this look (code, HTML and UI, so everyone can chip in a review :-p)

**Comment by tammoterhark** [comment]
Well, it works. Why only for article?

From a editor standpoint: when defining the page and having written a lot, having the buttons at the bottom makes more sense than at the top.

Also when reviewing the page, I always rather see that the editors go all the way down, just to be sure that they have had the chance to see the whole page.

**Comment by matthijskooijman** [comment]
> From a editor standpoint: when defining the page and having written a lot, having the buttons at the bottom makes more sense than at the top.

That's exactly why it's only added for article right now: all other edit interfaces are fairly short, so you usually have the top buttons in view already (and having the buttons in view twice is probably a bit of overkill). I'm happy to duplicate the buttons in other places as well, though, if we think that makes sense?

**Comment by matthijskooijman** [comment]
> Also when reviewing the page, I always rather see that the editors go all the way down, just to be sure that they have had the chance to see the whole page.

@tammoterhark  that makes sense. I've just added a commit to removes the approve button from the top of the page and only shows it  at the bottom.

**Pull request merged**
