### PR TITLE
Fix regex, add comments

### LINKED ISSUE #306: Install new hypha fails (probably because of empty lang dropdown)
when creating a hypha.php to download the subsequent form has an empty language dropdown. On send a blank screen is shown and the install did not succeed

### PR DESCRIPTION
**Pull request by RoukePouw**
Fixes #306

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Hm, I'm a bit surprised about this, since:
 - This regex was introduced like this in a876c60 and I assume I would have tested this then (since the entire point of that commit was to fix hypha.php building).
 - The "m" flag in the regex should make `^` match the start of each line, not just the start of the string. E.g. from [the perl docs](https://perldoc.perl.org/perlre.html#Modifiers):
   > `m`
   > Treat the string being matched against as multiple lines. That is, change "^" and "$" from matching the start of the string's first line and the end of its last line to matching the start and end of each line within the string.

Even more, I just tested this here (PHP 7.3 on Ubuntu) and it seems it just works. If I go to hypha.php, fill in login details and click build, I get a hypha.php *with* data filled in. i.e.:

```
			//START_OF_DATA
			case 'index': $zip = "H4sIAAAAAAACA41U7W7CMAx8IWifAbFOTIJpYkj7iUJqICyJszih9O2X8k3dsv2L7k7O+WJH2RIOmdu6QbYNQkogGlBNAUwu0UNeoowGbDhK7om98AojMXyFFYFncEwgF8M+leawExvoEJcqIK88qd1WzOEnAnGXK0HAwCA2vLr0tQvI4FIE0VnkqzaTxWz6it4w7uxmjDbAgZvSwm5iapF7QGOiVVIEhZaxRRPWwgv1ULExGGoHlK/TlWovdDdLEIKyj43fWCOUTqxW1FM8Zaauo8LZVps3xgH4pYe9ggrKpfBBSQ3d0uy+gYyqq6Sqzentj8lxdJfS9nV2BTKjbLYjLlRrLwxwnL6V7ZA7HTedRMZu3FG3YYcuurRZRv/D9s1yCmBYohlWXjgHPn85b+EiBXUfXls3Rq1BNtPTW2rReqo2P9L6Gf2OJUxbU9LWzIvRy6zoYwsN7Q+lr91nmuMi9Hb54bH5ytJIv1kKPsr2RvHkzF83jok+oYkX/UVy2WTK7UNqN/x6Sq+LlvNwcnX5Zk+bHw7hF2MY1iqYBQAA"; break;
(... more data ...)
```

Are you sure this isn't working for you and the regex is the problem? Or could there some other factor that just coincides with your change in the regex?

**Comment by RoukePouw** [comment]
I'm tried a clean install again and now it did work :-S I'm thoroughly lost what went wrong yesterday. 

In my download folder I still have 27kb hypha.php files that do not have the file data replaced, downloaded after I did a clean install yesterday. 

I then altered to code echo instead of download the file to directly see what was happening, when I changed the regex I finally saw the data in the output. I then re-enabled the download and ended up with correct 695kb files.

**Comment by matthijskooijman** [comment]
Hm, something weird is going on. However, that makes it likely that the regex was not the actual problem, and this PR will not really fix anything.

I'm inclined to close this PR, for that reason.

If you can manage to reproduce the problem, we can try to figure out what is wrong and fix it (in #306), but if not, I'm also inclined to just close that issue.

**Comment by RoukePouw** [comment]
> I'm inclined to close this PR, for that reason. [...] I'm also inclined to just close that issue.

Agreed :-) If I stumble upon it happening again I'll reopen it.

**Pull request closed without merging**
