### PR TITLE
peer_reviewed_article: different labels for comments and sub-comments

### PR DESCRIPTION
**Pull request by laurensmartina**
Users can distinguish between comments and sub-comments.

### CODE REVIEW

**Comment by dianawi** [comment]
I prefer the last. Nice if it resembles a readable sentence.

**Comment by dianawi** [comment]
I had already introduced line "art-discussion" => "join the discussion" in the language files, line 327, for the same purpose. This gives the reader a choice whether they want to comment on the article or join an existing discussion.

**Comment by tammoterhark** [comment]
I am a bit lost. How to proceed? Discussion, @dianawi ?

**Comment by matthijskooijman** [comment]
PR #228 says it replaces this one. I haven't reviewed that one yet, though.

**Comment by dianawi** [comment]
can we just merge one?

**Comment by dianawi** [comment]
I suggest we merge this one and forget about #228.

**Comment by matthijskooijman** [comment]
This is replaced by #228, which was just merged.

**Pull request closed without merging**
